import {
  Bot,
  Braces,
  Clapperboard,
  Code2,
  FileSearch,
  Palette,
  PanelsTopLeft,
  Repeat2,
  Sparkles,
  WandSparkles,
  Workflow,
} from "lucide-react";

export const navItems = [
  { label: "Home", href: "/" },
  { label: "Workflows", href: "/workflows" },
  { label: "Tools", href: "/tools" },
  { label: "Services", href: "/services" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

export const workflows = [
  {
    slug: "claude-code-n8n-automation",
    title: "Claude Code + n8n Automation",
    category: "Automation",
    icon: Workflow,
    description: "Turn plain-language ideas into reliable automations with an AI coding partner.",
    difficulty: "Intermediate",
    estimatedTime: "90 min",
    tools: ["claude-code", "n8n"],
    outcome: "A tested automation with clear inputs, error handling, and reusable documentation.",
    prerequisites: ["A basic n8n workspace", "One repetitive process to automate"],
    steps: ["Map the trigger and desired result", "Draft the workflow with Claude Code", "Build and connect nodes in n8n", "Test failure cases and document the system"],
  },
  {
    slug: "claude-code-higgsfield-product-ads",
    title: "Claude Code + Higgsfield Product Ads",
    category: "Creative",
    icon: Clapperboard,
    description: "Build a repeatable product-ad pipeline from concept and prompts to export.",
    difficulty: "Intermediate",
    estimatedTime: "75 min",
    tools: ["claude-code", "higgsfield"],
    outcome: "A repeatable creative brief and prompt pipeline for product video concepts.",
    prerequisites: ["Product images", "A clear audience and offer"],
    steps: ["Structure the creative brief", "Generate scene and hook variants", "Create shots in Higgsfield", "Review and package winning concepts"],
  },
  {
    slug: "ai-news-carousel",
    title: "AI News Carousel Workflow",
    category: "Content",
    icon: Repeat2,
    description: "Research, structure, write, and design timely social carousels in less time.",
    difficulty: "Beginner",
    estimatedTime: "45 min",
    tools: ["perplexity", "claude", "canva"],
    outcome: "A sourced, structured social carousel ready for design and publishing.",
    prerequisites: ["A topic or news angle", "A preferred social channel"],
    steps: ["Collect and verify sources", "Find the useful audience angle", "Draft the slide narrative", "Design, review, and publish"],
  },
  {
    slug: "perplexity-notebooklm-research",
    title: "AI Research With Perplexity + NotebookLM",
    category: "Research",
    icon: FileSearch,
    description: "Move from open-web discovery to a grounded, organized research library.",
    difficulty: "Beginner",
    estimatedTime: "50 min",
    tools: ["perplexity", "notebooklm"],
    outcome: "A source-grounded research notebook with themes, evidence, and next actions.",
    prerequisites: ["A focused research question"],
    steps: ["Discover credible sources", "Import the strongest material", "Ask grounded synthesis questions", "Export findings and citations"],
  },
  {
    slug: "ai-website-builder",
    title: "AI Website Builder Workflow",
    category: "Build",
    icon: PanelsTopLeft,
    description: "Plan, generate, refine, and publish a focused website without tool chaos.",
    difficulty: "Intermediate",
    estimatedTime: "3 hours",
    tools: ["claude-code", "codex", "vercel"],
    outcome: "A responsive, production-ready website with a clear conversion path.",
    prerequisites: ["A defined offer", "Basic brand direction"],
    steps: ["Define the page strategy", "Generate the structure and design system", "Build and validate responsive pages", "Deploy and verify the live site"],
  },
  {
    slug: "tiktok-digital-product-funnel",
    title: "TikTok to Digital Product Funnel",
    category: "Growth",
    icon: Sparkles,
    description: "Connect short-form content to a simple lead magnet and digital offer.",
    difficulty: "Beginner",
    estimatedTime: "2 hours",
    tools: ["chatgpt", "capcut", "canva"],
    outcome: "A simple content-to-email funnel with a clear next step and reusable assets.",
    prerequisites: ["A narrow audience problem", "A simple digital offer"],
    steps: ["Define the content hook", "Create the lead magnet", "Build the landing path", "Publish and review conversion signals"],
  },
] as const;

export const tools = [
  { slug: "chatgpt", name: "ChatGPT", category: "AI Assistants", icon: Bot, description: "A versatile assistant for ideation, analysis, writing, and multimodal tasks.", bestFor: ["Brainstorming", "Writing", "Data analysis"], level: "Beginner", relatedWorkflows: ["ai-news-carousel", "tiktok-digital-product-funnel"] },
  { slug: "claude", name: "Claude", category: "AI Assistants", icon: Bot, description: "A thoughtful assistant for long documents, structured writing, and complex reasoning.", bestFor: ["Long-form work", "Analysis", "Content systems"], level: "Beginner", relatedWorkflows: ["ai-news-carousel"] },
  { slug: "gemini", name: "Gemini", category: "AI Assistants", icon: Bot, description: "Google's multimodal assistant with strong Workspace integration.", bestFor: ["Workspace tasks", "Multimodal prompts", "Research support"], level: "Beginner", relatedWorkflows: [] },
  { slug: "perplexity", name: "Perplexity", category: "AI Research", icon: FileSearch, description: "An answer engine for fast web discovery with visible source citations.", bestFor: ["Source discovery", "Current topics", "Research briefs"], level: "Beginner", relatedWorkflows: ["ai-news-carousel", "perplexity-notebooklm-research"] },
  { slug: "notebooklm", name: "NotebookLM", category: "AI Research", icon: FileSearch, description: "A grounded research workspace that answers from the sources you provide.", bestFor: ["Source synthesis", "Study guides", "Knowledge bases"], level: "Beginner", relatedWorkflows: ["perplexity-notebooklm-research"] },
  { slug: "claude-code", name: "Claude Code", category: "AI Coding", icon: Code2, description: "An agentic coding tool for understanding, changing, and testing complete codebases.", bestFor: ["Codebase work", "Automation design", "Rapid prototypes"], level: "Intermediate", relatedWorkflows: ["claude-code-n8n-automation", "claude-code-higgsfield-product-ads", "ai-website-builder"] },
  { slug: "codex", name: "Codex", category: "AI Coding", icon: Code2, description: "A coding agent for planning, implementation, testing, and repository workflows.", bestFor: ["Product builds", "Debugging", "Technical workflows"], level: "Intermediate", relatedWorkflows: ["ai-website-builder"] },
  { slug: "cursor", name: "Cursor", category: "AI Coding", icon: Code2, description: "An AI-first code editor for inline generation and repository-aware development.", bestFor: ["Editor-based coding", "Refactoring", "Code exploration"], level: "Intermediate", relatedWorkflows: ["ai-website-builder"] },
  { slug: "n8n", name: "n8n", category: "AI Automation", icon: Workflow, description: "A flexible visual automation platform for connecting apps, APIs, and AI steps.", bestFor: ["Business automation", "Agent workflows", "API orchestration"], level: "Intermediate", relatedWorkflows: ["claude-code-n8n-automation"] },
  { slug: "make", name: "Make", category: "AI Automation", icon: Workflow, description: "A visual no-code platform for approachable multi-app automations.", bestFor: ["Marketing operations", "App connections", "Simple scenarios"], level: "Beginner", relatedWorkflows: [] },
  { slug: "canva", name: "Canva", category: "AI Design", icon: Palette, description: "An accessible design platform for social content, presentations, and lead magnets.", bestFor: ["Social graphics", "Lead magnets", "Brand templates"], level: "Beginner", relatedWorkflows: ["ai-news-carousel", "tiktok-digital-product-funnel"] },
  { slug: "capcut", name: "CapCut", category: "AI Video", icon: Clapperboard, description: "A fast video editor for short-form content, captions, and social publishing.", bestFor: ["Short-form video", "Captions", "Social edits"], level: "Beginner", relatedWorkflows: ["tiktok-digital-product-funnel"] },
  { slug: "kling-ai", name: "Kling AI", category: "AI Video", icon: Clapperboard, description: "A generative video platform for cinematic motion and image-to-video work.", bestFor: ["Cinematic clips", "Image animation", "Concept scenes"], level: "Intermediate", relatedWorkflows: [] },
  { slug: "runway", name: "Runway", category: "AI Video", icon: Clapperboard, description: "A creative AI suite for video generation, editing, and visual effects.", bestFor: ["Generative video", "Visual effects", "Creative production"], level: "Intermediate", relatedWorkflows: [] },
  { slug: "heygen", name: "HeyGen", category: "AI Video", icon: Clapperboard, description: "An AI avatar and translation platform for presenter-led video production.", bestFor: ["Avatar videos", "Localization", "Explainers"], level: "Beginner", relatedWorkflows: [] },
  { slug: "higgsfield", name: "Higgsfield", category: "AI Video", icon: Clapperboard, description: "An AI video generation platform for cinematic camera motion and visual characters.", bestFor: ["Cinematic camera moves", "Visual characters", "Social media ads"], level: "Beginner", relatedWorkflows: ["claude-code-higgsfield-product-ads"] },
  { slug: "vercel", name: "Vercel", category: "AI Coding", icon: PanelsTopLeft, description: "A cloud platform for serverless deployment, hosting, and frontend framework integration.", bestFor: ["Frontend hosting", "Deploying web apps", "Production builds"], level: "Intermediate", relatedWorkflows: ["ai-website-builder"] },
  { slug: "tiktok", name: "TikTok", category: "AI Growth", icon: Sparkles, description: "A major short-form video hosting service used for organic reach and growth marketing.", bestFor: ["Short-form content", "Viral growth", "Lead generation"], level: "Beginner", relatedWorkflows: ["tiktok-digital-product-funnel"] },
] as const;

export const toolCategories = [...new Set(tools.map((tool) => tool.category))];

export const services = [
  { slug: "workflow-audit", title: "AI Workflow Audit", icon: FileSearch, description: "Find the friction, duplicate work, and best automation opportunities in your current process.", deliverables: ["Process map", "Priority opportunities", "Recommended tool stack"], timeline: "1 week" },
  { slug: "n8n-setup", title: "n8n Automation Setup", icon: Workflow, description: "Get a practical, maintainable automation built around the tools you already use.", deliverables: ["Production workflow", "Error handling", "Handover documentation"], timeline: "1–3 weeks" },
  { slug: "content-system", title: "AI Content System", icon: WandSparkles, description: "Create a repeatable research, writing, repurposing, and publishing workflow.", deliverables: ["Content operating system", "Prompt library", "Publishing workflow"], timeline: "2 weeks" },
  { slug: "website-chatbot", title: "Website + AI Chatbot", icon: PanelsTopLeft, description: "Launch a conversion-focused website with a useful, brand-aware AI assistant.", deliverables: ["Responsive website", "Knowledge-backed chatbot", "Analytics setup"], timeline: "3–5 weeks" },
  { slug: "custom-stack", title: "Custom AI Tool Stack", icon: Braces, description: "Choose and connect the right tools for your goals, budget, and technical comfort.", deliverables: ["Tool architecture", "Setup guidance", "Team playbook"], timeline: "1–2 weeks" },
] as const;
